"""rename address

Revision ID: 16282d590f2f
Revises: 40024cf4a818
Create Date: 2024-04-23 19:52:21.833373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16282d590f2f'
down_revision = '40024cf4a818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
