"""rename department

Revision ID: 40024cf4a818
Revises: 44eafa21d1fa
Create Date: 2024-04-23 19:50:58.594556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40024cf4a818'
down_revision = '44eafa21d1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
